---
- name: Clone repository
  git: repo={{ git_repo }} dest={{ dist_location }}

- name: Create virtualenv and install requirements
  pip: requirements={{ dist_location }}/requirements.txt virtualenv_command='virtualenv -p /usr/bin/python2' virtualenv={{ base_dir }}/{{ venv_name }}

- name: Install application
  pip: name={{ dist_location }}/. extra_args='-U' virtualenv={{ base_dir }}/{{ venv_name }}

- name: Create run directory
  file: state=directory path={{ base_dir }}/run

- name: Install supervisor configuration
  template: src=cb_supervisor.j2 dest={{ base_dir }}/cb_supervisor.conf

- name: Install application configuration
  template: src={{ item }}.j2 dest={{ base_dir }}/{{ item }}.py
  with_items:
    - api_config
    - workers_config

- name: Migrate database
  # command won't work here because it does not read env vars
  shell: chdir={{ dist_location }} CB_API_SETTINGS={{ base_dir }}/api_config.py {{ base_dir }}/{{ venv_name }}/bin/cb_manage db upgrade

- name: Shutdown supervisor
  command: "{{ base_dir }}/{{ venv_name }}/bin/supervisorctl -c {{ base_dir }}/cb_supervisor.conf shutdown"

- name: Start supervisor
  command: "{{ base_dir }}/{{ venv_name }}/bin/supervisord -c {{ base_dir }}/cb_supervisor.conf"

- name: Remove web direcory
  command: rm -rf {{ web_location }}

- name: Copy web
  command: cp -R {{ dist_location }}/web {{ web_location }}

- name: Install AngularJS
  command: chdir={{ web_location }} ~/node_modules/.bin/bower install angular

- name: Install Bootstrap
  command: chdir={{ web_location }} ~/node_modules/.bin/bower install bootstrap

# - name: Restart supervisor jobs
#   supervisorctl: name={{ item }} state=stopped config={{ base_dir }}/cb_supervisor.conf supervisorctl_path={{ base_dir }}/{{ venv_name }}/bin/supervisorctl
#   with_items:
#     - cb_api
#     - cb_workers
