---
- name: Verify sudo access
  shell: ls /dev/null
  sudo: True

- name: Clone repository
  git: repo={{ git_repo }}
       dest={{ dist_location }}
       version={{ git_tag }}

- name: Create virtualenv and install requirements
  pip: requirements={{ dist_location }}/prod-requirements.txt
       virtualenv={{ base_dir }}/{{ venv_name }}

- name: Install application
  pip: name={{ dist_location }}/.
       extra_args='-U'
       virtualenv={{ base_dir }}/{{ venv_name }}

- name: Create run directory
  file: state=directory
        path={{ base_dir }}/run

- name: Install supervisor configuration
  template: src=cb_supervisor.j2
            dest={{ base_dir }}/cb_supervisor.conf

- name: Install application configuration
  template: src={{ item }}.j2
            dest={{ base_dir }}/{{ item }}.py
  with_items:
    - config

- name: Migrate database
  shell: chdir={{ dist_location }}
         CLPBRD_CONFIG={{ base_dir }}/config.py {{ base_dir }}/{{ venv_name }}/bin/cb_manage db upgrade

- name: Install logrotate configuration
  sudo: True
  template: src=logrotate.j2
            dest={{ logrotate_config_dir }}/clapperboard

- name: Shutdown supervisor
  command: "supervisorctl -c {{ base_dir }}/cb_supervisor.conf shutdown"

- name: Start supervisor
  command: "supervisord -c {{ base_dir }}/cb_supervisor.conf"

- name: Create nginx sites directory
  sudo: True
  file: state=directory
        path=/etc/nginx/sites

- name: Copy nginx site config
  sudo: True
  template: src=nginx.j2
            dest=/etc/nginx/sites/clapperboard_v2
  notify:
    - reload nginx