"""Add admin user

Revision ID: 19455c843cb
Revises: 201d00eaaf0
Create Date: 2014-12-19 19:31:50.611645

"""

# revision identifiers, used by Alembic.
revision = '19455c843cb'
down_revision = '201d00eaaf0'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    connection = op.get_bind()

    users_table = sa.Table(
        'user',
        sa.MetaData(),
        sa.Column('id', sa.Integer, primary_key=True),
        sa.Column('username', sa.String),
        sa.Column('email', sa.String),
        sa.Column('password', sa.String),
    )

    if not connection.execute(users_table.select()).rowcount:
        connection.execute(
            users_table.insert().values(
                username='admin',
                email='admin@clpbrd.net',
                password=('pbkdf2:sha1:1000$JPMAoAxi$33c083a'
                          '4015ad939d386a8af22e49fa6fc8fe624')
                )
        )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # TODO: Add downgrade
    pass
    # ### end Alembic commands ###
