"""Add admin user

Revision ID: 19455c843cb
Revises: 201d00eaaf0
Create Date: 2014-12-19 19:31:50.611645

"""

# revision identifiers, used by Alembic.
revision = '19455c843cb'
down_revision = '201d00eaaf0'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.sql import table, column
from sqlalchemy import String, Integer


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    users_table = table(
        'user',
        column('id', Integer),
        column('username', String),
        column('email', String),
        column('password', String)
    )

    op.bulk_insert(
        users_table,
        [
            {
                'username': 'admin',
                'email': 'admin@clpbrd.net',
                # TODO: Find a better way to do this
                # clapperboard_changeme
                'password': ('pbkdf2:sha1:1000$JPMAoAxi$33c083a'
                             '4015ad939d386a8af22e49fa6fc8fe624')
            }
        ]
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # TODO: Add downgrade
    pass
    # ### end Alembic commands ###
