"""Add movie_metadata table

Revision ID: 1e0a099497
Revises: 19455c843cb
Create Date: 2014-12-20 09:55:25.739318

"""

# revision identifiers, used by Alembic.
revision = '1e0a099497'
down_revision = '19455c843cb'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'movie_metadata',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('data', sa.String(length=4096), nullable=True),
        sa.Column('movie_id', sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(['movie_id'], ['movie.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('movie_metadata')
    # ### end Alembic commands ###
