"""Make email a mandatory user attribute

Revision ID: 2f162d4a529
Revises: 41dad4131c6
Create Date: 2014-12-23 10:14:33.669110

"""

# revision identifiers, used by Alembic.
revision = '2f162d4a529'
down_revision = '41dad4131c6'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    connection = op.get_bind()
    users_table = sa.Table(
        'user',
        sa.MetaData(),
        sa.Column('id', sa.Integer, primary_key=True),
        sa.Column('username', sa.String),
        sa.Column('email', sa.String),
        sa.Column('password', sa.String),
        sa.Column('active', sa.Boolean)
    )

    connection.execute(
        users_table.update().where(
            users_table.c.email == None
        ).values(
            email='_'
        )
    )

    op.alter_column(
        'user', 'email',
        existing_type=mysql.VARCHAR(length=255),
        nullable=False
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'user', 'email',
        existing_type=mysql.VARCHAR(length=255),
        nullable=True
    )
    # ### end Alembic commands ###
