"""Add unique constraints

Revision ID: 36da47274bd7
Revises: 461fe3224e3f
Create Date: 2014-12-05 20:40:07.619245

"""

# revision identifiers, used by Alembic.
revision = '36da47274bd7'
down_revision = '461fe3224e3f'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'technology', ['code'])
    op.create_unique_constraint(None, 'theatre', ['url_code'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'theatre', type_='unique')
    op.drop_constraint(None, 'technology', type_='unique')
    # ### end Alembic commands ###
