"""Add email_verified column to user table

Revision ID: 41dad4131c6
Revises: 1e0a099497
Create Date: 2014-12-23 09:16:17.632235

"""

# revision identifiers, used by Alembic.
revision = '41dad4131c6'
down_revision = '1e0a099497'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'user',
        sa.Column('email_verified', sa.Boolean(), nullable=False)
    )

    connection = op.get_bind()
    users_table = sa.Table(
        'user',
        sa.MetaData(),
        sa.Column('id', sa.Integer, primary_key=True),
        sa.Column('username', sa.String),
        sa.Column('email', sa.String),
        sa.Column('password', sa.String),
        sa.Column('email_verified', sa.Boolean)
    )

    # Verify admin's email automatically
    connection.execute(
        users_table.update().where(
            users_table.c.id == 1
        ).values(
            email_verified=True
        )
    )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'email_verified')
    # ### end Alembic commands ###
